cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=single
  - mem_mb=50000
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 5
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True

use-singularity: True
singularity-args: "--bind /mnt/sds-hd/sd17l002/p/resolve_glioblastoma/data/:/data"